import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { extractRows, modifierIdsByVersion, modifierListIdsByVersion } from '../src/extract.js';

const here = dirname(fileURLToPath(import.meta.url));
const load = (name) => JSON.parse(readFileSync(join(here, 'fixtures', name), 'utf8'));

const { orders, catalog_objects: catalogObjects } = load('square-api.json');
const expected = load('expected-rows.json');
const catalogById = Object.fromEntries(catalogObjects.map((o) => [o.id, o]));

test('the ported parser reproduces the Python output exactly', () => {
  // The fixture is generated by scripts/make_worker_fixture.py from the
  // implementation that has been running in production.
  assert.deepEqual(extractRows(orders, catalogById), expected);
});

test('a refunded order with no total_money reads as 0 USD', () => {
  const rows = extractRows(orders, catalogById);
  const refunded = rows.find((r) => r.order_id === 'ORDER_REFUNDED');
  assert.ok(refunded, 'the refunded order should still produce a row');
  assert.equal(refunded.total_money, '0 USD');
});

test('"Question: Answer" in a modifier name is split', () => {
  const rows = extractRows(orders, catalogById);
  const row = rows.find((r) => r.order_id === 'ORDER_1');
  assert.equal(row.scout_name, 'John Smith');
});

test('a bare question with no answer records Unknown', () => {
  const row = extractRows([{
    id: 'O', created_at: '', total_money: { amount: 1, currency: 'USD' },
    line_items: [{ uid: 'L', name: 'Camp', modifiers: [{ name: 'Rank' }] }],
  }], {})[0];
  assert.equal(row.rank, 'Unknown');
});

test('an unrecognised question is ignored rather than guessed at', () => {
  const row = extractRows([{
    id: 'O', created_at: '', total_money: null,
    line_items: [{ uid: 'L', name: 'Camp', modifiers: [{ name: 'Shoe Size: 11' }] }],
  }], {})[0];
  assert.deepEqual(
    Object.entries(row).filter(([, v]) => v !== '' && v !== 'O' && v !== 'L' && v !== 'Camp'
      && v !== '0 USD'),
    [],
  );
});

test('a modifier list supplies the question when the modifier is the answer', () => {
  const catalog = {
    MOD: { id: 'MOD', modifier_data: { name: 'Tenderfoot', modifier_list_id: 'LIST' } },
    LIST: { id: 'LIST', modifier_list_data: { name: 'Rank' } },
  };
  const row = extractRows([{
    id: 'O', created_at: '', total_money: null,
    line_items: [{ uid: 'L', name: 'Camp', modifiers: [{ catalog_object_id: 'MOD' }] }],
  }], catalog)[0];
  assert.equal(row.rank, 'Tenderfoot');
});

test('a list name carrying its own answer is not duplicated', () => {
  const catalog = {
    MOD: { id: 'MOD', modifier_data: { name: 'Eagle', modifier_list_id: 'LIST' } },
    LIST: { id: 'LIST', modifier_list_data: { name: 'Patrol: Eagle' } },
  };
  const row = extractRows([{
    id: 'O', created_at: '', total_money: null,
    line_items: [{ uid: 'L', name: 'Camp', modifiers: [{ catalog_object_id: 'MOD' }] }],
  }], catalog)[0];
  assert.equal(row.patrol, 'Eagle');
});

test('a list name with a different answer appends the modifier', () => {
  const catalog = {
    MOD: { id: 'MOD', modifier_data: { name: 'Hawk', modifier_list_id: 'LIST' } },
    LIST: { id: 'LIST', modifier_list_data: { name: 'Patrol: Eagle' } },
  };
  const row = extractRows([{
    id: 'O', created_at: '', total_money: null,
    line_items: [{ uid: 'L', name: 'Camp', modifiers: [{ catalog_object_id: 'MOD' }] }],
  }], catalog)[0];
  assert.equal(row.patrol, 'Eagle - Hawk');
});

test('catalog ids are grouped by catalog version', () => {
  const byVersion = modifierIdsByVersion(orders);
  assert.ok(byVersion.size >= 2, 'the fixture spans more than one catalog version');
  for (const [version, ids] of byVersion) {
    assert.equal(typeof version, 'number');
    assert.ok(ids.size > 0);
  }
});

test('modifier lists are only fetched when not already loaded', () => {
  const withoutLists = Object.fromEntries(
    catalogObjects.filter((o) => !o.modifier_list_data).map((o) => [o.id, o]),
  );
  const pending = modifierListIdsByVersion(orders, withoutLists);
  const all = [...pending.values()].flatMap((set) => [...set]);
  assert.ok(all.includes('MODIFIER_LIST_1'), 'the referenced list should be queued');

  // Once loaded, it should not be requested again.
  assert.equal(
    [...modifierListIdsByVersion(orders, catalogById).values()].flatMap((s) => [...s]).length,
    0,
  );
});

test('every row carries a usable primary key', () => {
  for (const row of extractRows(orders, catalogById)) {
    assert.ok(row.order_id, 'order_id');
    assert.ok(row.line_item_uid, 'line_item_uid');
  }
});

test('the email comes from a pickup fulfillment recipient', () => {
  const row = extractRows(orders, catalogById).find((r) => r.order_id === 'ORDER_1');
  assert.equal(row.email, 'john.smith@example.com');
});

test('a shipment fulfillment works too', () => {
  const row = extractRows(orders, catalogById).find((r) => r.order_id === 'ORDER_2');
  assert.equal(row.email, 'jane.doe@example.com');
});

test('an order with only a customer_id has no inline email', () => {
  // sync.js fills these in with a Customers lookup.
  const row = extractRows(orders, catalogById).find((r) => r.order_id === 'ORDER_3');
  assert.equal(row.email, '');
  assert.equal(row.customer_id, 'CUSTOMER_3');
});

test('an order with no fulfillment and no customer yields empty, not undefined', () => {
  const row = extractRows([{
    id: 'O', created_at: '', total_money: null,
    line_items: [{ uid: 'L', name: 'Camp' }],
  }], {})[0];
  assert.equal(row.email, '');
  assert.equal(row.customer_id, '');
});

test('the first recipient with an email wins', () => {
  const row = extractRows([{
    id: 'O', created_at: '', total_money: null,
    fulfillments: [
      { pickup_details: { recipient: {} } },
      { shipment_details: { recipient: { email_address: 'second@example.com' } } },
    ],
    line_items: [{ uid: 'L', name: 'Camp' }],
  }], {})[0];
  assert.equal(row.email, 'second@example.com');
});
